### ISSUE TITLE
Ref errors everywhere

### ISSUE THREAD

**Issue by AlexDumo** [OpenMarch/OpenMarch#250]
Since the new UI update, there have been ref errors popping up when launching new components. 

This isn't specifically for one component. It appears when the marcher editor pops up as well as a handful of other components

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `SlotClone`.
    at DialogTrigger (http://localhost:5173/src/components/ui/Dialog.tsx:28:3)
    at http://localhost:5173/node_modules/.vite/deps/chunk-7RYZD3AP.js?v=81ca8c55:69:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-7RYZD3AP.js?v=81ca8c55:49:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-7RYZD3AP.js?v=81ca8c55:149:13
    at http://localhost:5173/node_modules/.vite/deps/chunk-7RYZD3AP.js?v=81ca8c55:69:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-7RYZD3AP.js?v=81ca8c55:49:11
    at http://localhost:5173/node_modules/.vite/deps/chunk-7RYZD3AP.js?v=81ca8c55:149:13
    at http://localhost:5173/node_modules/.vite/deps/chunk-MJ3S2WEJ.js?v=81ca8c55:1976:13
    at http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=81ca8c55:185:13
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-WUBLEWJB.js?v=81ca8c55:40:15)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-MJ3S2WEJ.js?v=81ca8c55:1908:15)
    at Popper (http://localhost:5173/node_modules/.vite/deps/chunk-MJ3S2WEJ.js?v=81ca8c55:1968:11)
    at Tooltip (http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=81ca8c55:101:5)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-WUBLEWJB.js?v=81ca8c55:40:15)
    at Dialog (http://localhost:5173/node_modules/.vite/deps/chunk-AKA6WT5D.js?v=81ca8c55:48:5)
    at Dialog (http://localhost:5173/src/components/ui/Dialog.tsx:21:26)
    at ExportCoordinatesModal
    at div
    at FileControls
    at div
    at div
    at TitleBar (http://localhost:5173/src/components/titlebar/TitleBar.tsx?t=1733666499997:22:36)
    at FieldPropertiesProvider (http://localhost:5173/src/context/fieldPropertiesContext.tsx:29:43)
    at SelectedAudioFileProvider (http://localhost:5173/src/context/SelectedAudioFileContext.tsx:23:3)
    at SelectedMarchersProvider (http://localhost:5173/src/context/SelectedMarchersContext.tsx:29:3)
    at SelectedPageProvider (http://localhost:5173/src/context/SelectedPageContext.tsx:28:40)
    at IsPlayingProvider (http://localhost:5173/src/context/IsPlayingContext.tsx:22:37)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-WUBLEWJB.js?v=81ca8c55:40:15)
    at TooltipProvider (http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=81ca8c55:57:5)
    at main
    at App (http://localhost:5173/src/App.tsx?t=1733666499997:45:49)
    at ThemeProvider (http://localhost:5173/src/context/ThemeContext.tsx:34:33)
    ```

**Comment by AlexDumo** [comment]
This can be fixed by using `React.ForwardRef`
